workflows:
  ios-build:
    name: Build iOS app
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_VERSION: 3.24.0
    scripts:
      - name: Install dependencies
        script: |
          flutter --version
          flutter pub get
          gem install cocoapods
      - name: Clean and update Pods
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod cache clean --all
          pod repo update
          pod install
      - name: Clean Flutter build
        script: |
          flutter clean
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Archive iOS build
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration AppStoreDistribution archive -archivePath build/Runner.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath build/ios/iphoneos
    artifacts:
      - build/ios/iphoneos/*.ipa
