name: Build & Release

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set execute permissions for gradlew
        run: chmod +x android/gradlew

      - name: Clean up build directory to save space
        run: rm -rf build

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Cache Flutter and Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get

      - name: Clean project with Gradle
        run: ./android/gradlew clean
        shell: bash

      - name: Build APK
        run: |
          export ORG_GRADLE_CACHING=false
          ./android/gradlew assembleRelease
          if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
            echo "APK not found!"
            exit 1
          fi
        shell: bash

      - name: List APK Directory
        run: ls -R build/app/outputs/flutter-apk

      - name: Check if iOS Directory Exists
        run: |
          if [ ! -d "ios" ]; then
            echo "iOS directory not found!"
            exit 1
          fi

      - name: Update CocoaPods
        run: |
          cd ios
          pod repo update
          pod install
        shell: bash

      - name: Build iOS App
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          zip -r Etqan.ipa Runner.app

      - name: Check if APK and IPA exist
        run: |
          if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
            echo "APK not found!"
            exit 1
          fi
          if [ ! -f build/ios/iphoneos/Etqan.ipa ]; then
            echo "IPA not found!"
            exit 1
          fi
        shell: bash

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/ios/iphoneos/Etqan.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
